# Generated by Django 5.0.1 on 2024-01-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerinfo',
            name='selleremail',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sellerinfo',
            name='sellerphone',
            field=models.CharField(max_length=15),
        ),
    ]
