# Generated by Django 5.0.1 on 2024-01-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_sellerinfo_selleremail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='pin',
        ),
    ]
