# Generated by Django 5.0.1 on 2024-01-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_remove_customer_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='type',
        ),
    ]
