# Generated by Django 5.0.1 on 2024-01-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FileField(upload_to=''),
        ),
    ]
